//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LucaWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RICHIESTEEntities : DbContext
    {
        public RICHIESTEEntities()
            : base("name=RICHIESTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProdottiSet> ProdottiSet { get; set; }
        public virtual DbSet<RichiesteProdotti> RichiesteProdotti { get; set; }
        public virtual DbSet<RichiesteSet> RichiesteSet { get; set; }
    
        public virtual ObjectResult<CercaPerCodice_Result> CercaPerCodice(Nullable<int> idCod)
        {
            var idCodParameter = idCod.HasValue ?
                new ObjectParameter("idCod", idCod) :
                new ObjectParameter("idCod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CercaPerCodice_Result>("CercaPerCodice", idCodParameter);
        }
    
        public virtual ObjectResult<CercaPerDescrizione_Result> CercaPerDescrizione(string descr)
        {
            var descrParameter = descr != null ?
                new ObjectParameter("descr", descr) :
                new ObjectParameter("descr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CercaPerDescrizione_Result>("CercaPerDescrizione", descrParameter);
        }
    }
}
